import { Inter } from "next/font/google";
import "./globals.css";
import Reduxprovider from "@/provider/redux/Reduxprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Reduxprovider>
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
    </Reduxprovider>
  );
}
